### ISSUE TITLE
Stuck after teleport

### ISSUE THREAD

**Issue by deezar** [OpenKore/openkore#213]
From http://forums.openkore.com/viewtopic.php?f=56&t=12171.
This bug is quite common. If you've set your bot to teleport often you'll likely experience it. Bot will stuck doing nothing after teleport (sometimes, before teleport when bad connection) causing frequent deaths.

It remains unresolved and has been with us since I can remember. People suggesting workarounds using macros and they help a bit but not close to perfect. I think it's worth revisiting this bug here once we move to GitHub.

The macro that seems to work is by issuing a `warp cancel` command after each teleportation. But it's still...just a workaround. Better have this inherently fixed in the source.

@kLabMouse said it might be a race condition problem and I seem to agree.
http://forums.openkore.com/viewtopic.php?p=54651#p54651

**Comment by AlexandreBR3N** [comment]
I don't know if it works but : 

http://forums.openkore.com/viewtopic.php?f=36&t=211603&p=274520&hilit=teleport#p274520

**Comment by alisonrag** [comment]
fixed at #3192

**Comment by kyloren23** [comment]
hello im still having this issue as of 2023 my only solution is spam enter every 10sec using ahk macro controlsend feature.. but some ro have protection from macro software and dont work
