### ISSUE TITLE
xconf or pickupitems not working as it should

### ISSUE THREAD

**Issue by nizdi** [OpenKore/openkore#2543]
xconf (pconf) is adding Item ID in pickupitems.txt, but Kore is not picking up items unless I put the name, like Orc Claw instead of 1043 (Orc Claw ID).

When I use pconf Orc Claw 2, it goes to pickupitems as 1043 2 # Orc Claw, but it wont pick it, unless i put the name.

100% reproduction.

I dont know if the problem is with xconf inserting item as ID, or is at pickupitem doesnt picking ID numbers.

https://i.imgur.com/HiawmTe.png

**Comment by Fadreus** [comment]
![image](https://user-images.githubusercontent.com/32188494/49714627-8b712500-fc88-11e8-9568-23d252cf0bd6.png)

Latest version have no problem.

**Comment by Fadreus** [comment]
![image](https://user-images.githubusercontent.com/32188494/49714627-8b712500-fc88-11e8-9568-23d252cf0bd6.png)

![image](https://user-images.githubusercontent.com/32188494/49714703-e73bae00-fc88-11e8-825b-8b99598f22c5.png)


Latest version have no problem.
Working fine as it should.
Check your setting again.

**Comment by Fadreus** [comment]
![image](https://user-images.githubusercontent.com/32188494/49714627-8b712500-fc88-11e8-9568-23d252cf0bd6.png)

![image](https://user-images.githubusercontent.com/32188494/49718958-afd3fe00-fc96-11e8-81ca-a87bc11fa25f.png)

Latest version have no problem.
Working fine as it should.
Check your setting again.

**Comment by nizdi** [comment]
@Fadreus I'm so sorry, i thought mine was sync automatic, i'm doing it by hand now and gonna check. I'll come back.

**Comment by Fadreus** [comment]
I'm more intrigue on `curinha2` while default must be `control`.
Do you use some thing like openkore manager; which not from openkore?

> When you use pconf ITEM it shows last status of picking up this item, or shows as none for you too?

To answer your question, if the item didn't exist, it will be added.

**Comment by Fadreus** [comment]
If I were you, I ditch `profile.pl` and use [this](http://www.openkore.com/index.php/Run_multiple_bots_from_the_same_.exe?hc_location=ufi).

**Comment by Nipodemos** [comment]
I think the problem was the comments that keep in front of item ID
when you use the pconf command, it automatically insert this comment, which confuses the regexes

For us to be sure, use this command on your openkore (after using pconf with ID)
`eval use Data::Dumper; warning (Dumper(\%pickupitems)) ;`

This will show some yellow lines, send us the print of this please

**Comment by nizdi** [comment]
![image](https://user-images.githubusercontent.com/29477616/49738102-ab4b1d80-fc75-11e8-81e4-46b620bb0aec.png)

Item is Skeleton Bone (ID = 932) now.

@Fadreus but the problem persist even without profiles. I'll reconsidering using it, but I just wanted xconf.pl to work, it's so damn useful. And if i'm not wrong, it worked with before, it's only showing problems now.

**Comment by Fadreus** [comment]
There is 1 thing weird.
Why raiseStat always appear ?
Normally it just this
![image](https://user-images.githubusercontent.com/32188494/49738869-6c47b700-fccb-11e8-963a-d9e230490e55.png)

**Comment by Fadreus** [comment]
1 thing is weird; why raiseStat always appear?
It should be just this:
![image](https://user-images.githubusercontent.com/32188494/49738987-bb8de780-fccb-11e8-8c04-a28307b0e9be.png)

**Comment by nizdi** [comment]
I don't know, it always appear when I reload something from control folder. I'll check again at home, but maybe a plugin problem? I'll try disable some plugins to take a look, but I was just used to it appearing. The condition to add stats is off in config.txt tho.

Obter o Outlook para Android<https://aka.ms/ghei36>

________________________________

**Comment by Nipodemos** [comment]
@nizdi if you pay attention to fadreus print, you'll notice the there isn't a comment in front of item, that's why it works on his openkore

Fortunaly, the problem was already solved today by @lututui, just update your openkore again and it will probably work

**Comment by nizdi** [comment]
I'll try again at home but it's weird since I downloaded the new openkore already with the pull from lututui, but I'll see it again.
I just did not understood why fadreus had the same version as me and the results were different.

**Comment by nizdi** [comment]
Still not working.

![image](https://user-images.githubusercontent.com/29477616/49755022-e6157b80-fc9e-11e8-8d9e-419c26e6afc4.png)

My pickupitems still using this structure:

`932 2 # Skeleton Bone`

Which might be the problem as you said.

Also, @Fadreus raiseStat is from the plugin in the default openkore

`################################################################
#  Hooks used to activate the plugin during initialization
#  and on config change events.
my $base_hooks = Plugins::addHooks(
	['start3',        \&checkConfig],
	['postloadfiles', \&checkConfig],
    ['configModify',  \&on_configModify]
   );`

Which, if I understand it right, it's gonna trigg whenever I make a modification in config files.

**Comment by Nipodemos** [comment]
@nizdi how are you updating your openkore? I just tested and seems to work fine for me, even with comments

**Comment by nizdi** [comment]
@Nipodemos through git sync. I'll download a fresh one right now again to try, my old folder could be broken idk.

**Comment by Fadreus** [comment]
Try run openkore on different platform or in VM.

**Comment by Fadreus** [comment]
You might wanna tell us what changes have you done with openkore and your PC since it last working that you claimed to be.

At this point, xConf is working fine.
Openkore also working fine.

Even if you could provide the reproduce step, I doubt the value would remain `none`
Put a comment before or after, if the value didn't exist, it will be written a new.
If the value exist, even if it incorrect, it would show old value.

Either way, I tried possible common mistakes and I can't reproduce as what happened to yours.

**Comment by Fadreus** [comment]
You might wanna tell us what changes have you done with openkore and your PC since it last working that you claimed to be.

At this point, xConf is working fine.
Openkore also working fine.

Even if you could provide the reproduce step, I doubt the value would remain `none`
Put a comment before or after, if the value didn't exist, it will be written a new.
If the value exist, even if it incorrect, it would show old value.

Either way, I tried possible common mistakes and I can't reproduce as what happened to yours.
Try run on different platform or in VM.

**Comment by c4c1n6kr3m1** [comment]
put the comment under your item's line, not on the same line, how's that ?
932 2
# Skeleton Bone

**Comment by c4c1n6kr3m1** [comment]
put the comment under your item's line, not on the same line, how's that ?

**Comment by nizdi** [comment]
> put the comment under your item's line, not on the same line, how's that ?

It's automatic put by the plugin after the ID + (-1,0,1,2) or I would. I dont know what to change in xConf.pl to change it.



> You might wanna tell us what changes have you done with openkore and your PC since it last working that you claimed to be.
> 
> At this point, xConf is working fine.
> Openkore also working fine.
> 
> Even if you could provide the reproduce step, I doubt the value would remain `none`
> Put a comment before or after, if the value didn't exist, it will be written a new.
> If the value exist, even if it incorrect, it would show old value.
> 
> Either way, I tried possible common mistakes and I can't reproduce as what happened to yours.
> Try run on different platform or in VM.

I know it's my computers problem. I'll try to run a VM since I can't try in another computer, but thanks for all the help.

**Comment by Nipodemos** [comment]
I just had the exact same problem, I I've noticed that it's not the plugin thing it's openkore
openkore is not removing comments, I'll try to make a pull request today to fix that

**Comment by Nipodemos** [comment]
@fadreus if you use pconf command to insert a new item on pickupitems (and use ID of item) you'll notice that you'll have the same problem

**Comment by Nipodemos** [comment]
I am almost sure that the problem occurs when you are not using default control folder

**Comment by Fadreus** [comment]
Okay. Now that you mention it, everything he said is making sense now.

**Comment by c4c1n6kr3m1** [comment]
@nizdi , for now, what if remove the additional comment from xconf.pl

, "#", $key
, "#", $name

**Comment by nizdi** [comment]
@c4c1n6kr3m1 it's working great now!!!

![image](https://user-images.githubusercontent.com/29477616/49827202-e7fb3f80-fd6f-11e8-9da2-f8755751e092.png)

As a quickfix changin lines 273 and 275 (comments) from xConf.pl is working.

**Comment by c4c1n6kr3m1** [comment]
lets wait someone make a proper fix for this rather than a trick , well i don't use this plugin nor profile plugin
may be @Nipodemos has found the culprit ?
