### ISSUE TITLE
Unable to connect to server - Official Vietnam Ragnarok (server uses nProtect Gameguard)

### ISSUE THREAD

**Issue by chrislong93** [OpenKore/openkore#3440]
## ------------------ Openkore Issues Template ------------------

* **Openkore version git**:  2.1

* **Server**: Vietnam Official (VTC Ragnarok Online)

* **Bug Report / Feature Request**: Unable to connect to server (server uses nProtect Gameguard)

* **Summary**: I have been able to extract IP & Port and version & master_version (using Wireshark). However, I stuck at "**connected**"

![image](https://user-images.githubusercontent.com/26244945/121005799-5f33b200-c7ba-11eb-8d65-4b13e82cae82.png)

I tried using Poseidon server also but the clientinfo.xml extracted using GRF is not similar to a clientinfo.xml template

```
<clientinfo>
	<servicetype>vietnam</servicetype>
	<servertype>primary</servertype>
	<passwordencrypt></passwordencrypt>
	<hideaccountlist></hideaccountlist>
	<extendedslot></extendedslot>
	
	<connection>
		<display>Vietnam Live</display>
		<desc>None</desc>
		<domain>roacc1.vtcgame.vn:6900</domain>
		<port>6900</port>
		<version>1</version>
		<registrationweb>http://www.ragnarok.co.kr</registrationweb>
		<aid>
			<admin>100001</admin><admin>100002</admin><admin>100003</admin><admin>100004</admin><admin>100005</admin><admin>100006</admin><admin>100007</admin><admin>100008</admin>
			<admin>100009</admin><admin>100010</admin><admin>100011</admin><admin>100012</admin><admin>100013</admin><admin>100014</admin><admin>100015</admin><admin>100016</admin>
			<admin>100017</admin><admin>100018</admin><admin>100019</admin><admin>100020</admin>
			
		</aid>
	</connection>

</clientinfo>
```

This server uses a custom client where you login ID & PW using a Patcher-like window, then the game will show up where you choose server & character. This was my steps using Wireshark:

**1) IP & Port**

![image](https://user-images.githubusercontent.com/26244945/121006720-6d360280-c7bb-11eb-93c9-2534470a5c51.png)

**2) Version & Master_version: Following TCP Stream I get this**

![image](https://user-images.githubusercontent.com/26244945/121006815-88087700-c7bb-11eb-9806-1dfddf767848.png)

I assume that the 1st line is version (from Hex **01** to Decimal: **1**)

3rd line is master_version (from Hex **61** to Decimal: **97**)

**Then I stuck at Timeout on Account Server.**

Other things I have tried but does not work:

- WPE Pro 0.9: cannot find exe file
- RO Tool to disarm: doesnt work
- PEEK master: doesnt work
- extract_packets.pl: cannot generate recvpackets from the exe

Please help or advice where you can. Thank you very much everyone!

Let me know if you need to official game download link or the exe file uploaded.

**Comment by alisonrag** [comment]
Is this a official server? I never heard about this. Can you provide the website link so we can add to official server list?

**Comment by vclvclvn** [comment]
the website: https://ro.vtcgame.vn/

**Comment by farsmile90** [comment]
Hi chrislong93, my name Thi, and I'm stuck exactly like you (connected, but timeout...) , really need support ASAP pls!

**Comment by chrislong93** [comment]
> Is this a official server? I never heard about this. Can you provide the website link so we can add to official server list?

@alisonrag  Hi there, thanks for noticing my post. It is an official server, right now its running a close beta week (until 12th of June) then will be open beta. Its officially distributed by VTC Games in Vietnam & Gravity.

I hope you guys can help in connecting to this server.

Website: https://ro.vtcgame.vn/
Download link: http://dl5.vtcgame.vn:8888/ragnarok/2021-06-07RO_CBT.exe

**Comment by Pureaznangel** [comment]
up!

**Comment by chrislong93** [comment]
up please help with this official server !

**Comment by Pureaznangel** [comment]
> up please help with this official server !

Relax! I'm waiting for him, too.

**Comment by vclvclvn** [comment]
share we donate to encourage the developer. For me, it's fine. I'm willing to do so to have it done.

**Comment by farsmile90** [comment]
Yeah, i love to donate if dev can make openkore run on VTC ragnarok. But let wait for the open beta first, now the server is close.

**Comment by antrinhht** [comment]
> up please help with this official server !

Can you share me your config you tested?

**Comment by vclvclvn** [comment]
they already do open beta. Could you help to check and make login config file?

**Comment by ya4ept** [comment]
![image](https://user-images.githubusercontent.com/7117363/124832628-96e27500-df85-11eb-85da-248348c6eda9.png)

**Comment by Pureaznangel** [comment]
It's ok! Try again now.

**Comment by vclvclvn** [comment]
Did anyone successfully config for this?

**Comment by chumlacklx** [comment]
Sever was open yesterday. Any developer success in finding sever address ? Plz reply and i can donate for you :)

Hello Chrislong, I'm vietnamese also =)) if you can plz contact and make friend via Facebook name Minh Triệu Đặng. I need a guild for vRO community

**Comment by ya4ept** [comment]
the server address is "roacc1.vtcgame.vn:6900", but it doesn't give anything

**Comment by Pureaznangel** [comment]
> the server address is "roacc1.vtcgame.vn:6900", but it doesn't give anything

https://www.yougetsignal.com/tools/open-ports/ gives me result that port is opening on the server. I'll try another shot on this afternoon.

Thankx!

**Comment by alisonrag** [comment]
> the server address is "roacc1.vtcgame.vn:6900", but it doesn't give anything

maybe ip block by region, here to login in other officials servers i need to use vpn

**Comment by ya4ept** [comment]
first prototype #3453

**Comment by chumlacklx** [comment]
sir ya4ept could you upload these file to openkore master plz ? i need to download zip file again for full features. I really don't know how to extract recvpackets.txt. Thank a lot !

**Comment by sctnightcore** [comment]
> sir ya4ept could you upload these file to openkore master plz ? i need to download zip file again for full features. I really don't know how to extract recvpackets.txt. Thank a lot !

if u read #3453 .

it has all file :p

**Comment by chumlacklx** [comment]
how to create .pm file sir scrnightcore ? i attempt to use note pad to make .pm file is it ok ?

**Comment by chumlacklx** [comment]
![image](https://user-images.githubusercontent.com/87187797/125151165-6100e480-e16f-11eb-861a-1824a3b66458.png)

still stuck :(

**Comment by Pureaznangel** [comment]
> > sir ya4ept could you upload these file to openkore master plz ? i need to download zip file again for full features. I really don't know how to extract recvpackets.txt. Thank a lot !
> 
> if u read #3453 .
> 
> it has all file 
Maybe I missed something but I could not find it, too. Please check.

**Comment by chumlacklx** [comment]
Anyone help with recvpacket.txt pls. It’s hard to extract i tried to use any tool helping extract on openkore ưiki but it doesn’t work

**Comment by alisonrag** [comment]
> Anyone help with recvpacket.txt pls. It’s hard to extract i tried to use any tool helping extract on openkore ưiki but it doesn’t work

the client ragexe is packed with themida, need to find or make a unpacker, then try to extract recvpackets

**Comment by ya4ept** [comment]
all is ready!

**Comment by chrislong93** [comment]
> > Anyone help with recvpacket.txt pls. It’s hard to extract i tried to use any tool helping extract on openkore ưiki but it doesn’t work
> 
> the client ragexe is packed with themida, need to find or make a unpacker, then try to extract recvpackets

Unpacking executable file packed with Themida is no smol task, it uses an extremely complex virtual machine environment combined with every anti-debug and anti-analysis trick in the books :(

**Comment by TheSunShower** [comment]
> all is ready!

It's connected and botable now. However, autobuy/autosell caused disconnection, and autostorage requires encryption key

**Comment by ya4ept** [comment]
@TheSunShower autosell is fixed: #3458
give me money for kafra, my name is `kirama`

**Comment by chumlacklx** [comment]
Glad to see everyone support on vRO. Thank so much

**Comment by TheSunShower** [comment]
Packet Parser: Unknown switch: 0918

**Comment by ya4ept** [comment]
@TheSunShower how to get this package? 
use `debugPacket_unparsed 2`

**Comment by ya4ept** [comment]
storage fixed: #3458

**Comment by c4c1n6kr3m1** [comment]
is it paid server? how to register ?

**Comment by ya4ept** [comment]
https://ro.vtcgame.vn/

**Comment by TheSunShower** [comment]
Auto attack works.

Self buff works.

Attack Skill doesn't work, it just stares at monsters. Config as followed:

#Main Config:

attackAuto 2
attackDistance 8
attackUseWeapon 0
lockMap yuno_fild08

#Skill Blocks:

attackSkillSlot Cold Bolt {
lvl 10
dist 8
sp > 18
inLockOnly 1
notInTown 1
monsters Grand Peco
}

attackSkillSlot Fire Bolt {
lvl 10
dist 8
sp > 18
inLockOnly 1
notInTown 1
monsters Geographer
}

**Comment by alisonrag** [comment]
> Auto attack works.
> 
> Self buff works.
> 
> Attack Skill doesn't work, it just stares at monsters. Config as followed:
> 
> #Main Config:
> 
> attackAuto 2
> attackDistance 8
> attackUseWeapon 0
> lockMap yuno_fild08
> 
> #Skill Blocks:
> 
> attackSkillSlot Cold Bolt {
> lvl 10
> dist 8
> sp > 18
> inLockOnly 1
> notInTown 1
> monsters Grand Peco
> }
> 
> attackSkillSlot Fire Bolt {
> lvl 10
> dist 8
> sp > 18
> inLockOnly 1
> notInTown 1
> monsters Geographer
> }

seems like skills name are different, check:
https://github.com/OpenKore/openkore/blob/master/tables/vRO/skillnametable.txt

type skills in console and try to use the same name, also try with:
`MG_FIREBOLT` and `MG_COLDBOLT`

**Comment by Pureaznangel** [comment]
Use skill Id, instead. => Info => Skill to get one.

**Comment by TheSunShower** [comment]
> type skills in console and try to use the same name, also try with:
> `MG_FIREBOLT` and `MG_COLDBOLT`

Skill ID didn't work. These names works however.

**Comment by Pureaznangel** [comment]
Failed to gather Red Herb (6) : Timeout
Gathering: Decayed Nail (8)
You tried too long to move
You tried too long to move
You tried too long to move
You tried too long to move
Disconnected from Map Server, connecting to Account Server in 48 seconds...

Disconnection occurred serveral times.

**Comment by chumlacklx** [comment]
![10FD561A-F403-4E78-846A-1ED431D9FF26](https://user-images.githubusercontent.com/87187797/125230754-a1916700-e303-11eb-9c97-42b9f6d18f97.jpeg)

can’t tele although have fly wing in inventory

**Comment by Pureaznangel** [comment]
> ![10FD561A-F403-4E78-846A-1ED431D9FF26](https://user-images.githubusercontent.com/87187797/125230754-a1916700-e303-11eb-9c97-42b9f6d18f97.jpeg)
> 
> can’t tele although have fly wing in inventory

teleportAuto_useSkill 0 <=== if Teleport skill is unvailable

teleportAuto_item1 Beginner's Fly Wing <====== or anything else
teleportAuto_item2

**Comment by TheSunShower** [comment]
The disconnection that happens frequently might be related to access token from VTC being timed out (No Msg 243)

On ROClient, a logout/login is required to restart a launcher with a timed out token

On OpenKore, need to physically close Terminal and relaunch OpenKore. If not it will gradually stack relog timer.

**Comment by ya4ept** [comment]
RO client can run longer openkore without restarting?
I need a test account with skills

**Comment by TheSunShower** [comment]
Example of disconnection on OpenKore

Connecting to Account Server...
Connecting (roacc1.vtcgame.vn:6900)... connected
Disconnecting (IP:6900)...disconnected
The server has denied your connection for unknown reason (243).

this is the point where OpenKore cannot reconnect itself anymore.

**Comment by ya4ept** [comment]
try this #3459

**Comment by PhiLongXP** [comment]
> 
> 
> try this #3459

Token is alive in 1hours only, so renew when connect that should work. 

Maybe this is ping-back send every 10 minutes. If there is no response in 3 times, will be disconnected from Map Server.
![image](https://user-images.githubusercontent.com/816743/125257631-d1526600-e327-11eb-9aae-964ec7fabb2d.png)

**Comment by playboyvntgn** [comment]
@ya4ept I can't use auto storage because they need EncryptKey. Do you know EncryptKey of vRo server? 
I appreciate your help!

**Comment by TheSunShower** [comment]
> I can't use auto storage because they need EncryptKey.

Fixed in latest master.

**Comment by playboyvntgn** [comment]
> > I can't use auto storage because they need EncryptKey.
> 
> Fixed in latest master.

Thank you I got it.

I have one more error, that's I can't use warp skill. After I cast it on ground, the bot disconnected immediately.

<img width="314" alt="dc" src="https://user-images.githubusercontent.com/10356162/125273156-d4a11e00-e336-11eb-8f26-bf5db57b8ba2.png">

**Comment by chrislong93** [comment]
> > I can't use auto storage because they need EncryptKey.
> 
> Fixed in latest master.

autobuy still not working with the latest vRo_auth.pl update?

**Comment by c4c1n6kr3m1** [comment]
send skill_use 0438
send skill_use_location 0366

**Comment by abc9900** [comment]
Disconnect from map after few sec inactive/idle, so follow config/command can't be used.

**Comment by chrislong93** [comment]
> > try this #3459
> 
> Token is alive in 1 hour only, so renew when connect that should work.
> 
> Maybe this is ping-back send every 10 minutes. If there is no response in 3 times (resend every minute), will be disconnected from Map Server.
> ![image](https://user-images.githubusercontent.com/816743/125257631-d1526600-e327-11eb-9aae-964ec7fabb2d.png)

this is still an on-going issue, havent been fixed in the latest master

**Comment by WHjskyJ** [comment]
![image](https://user-images.githubusercontent.com/87201145/125321907-5b6def00-e367-11eb-9f1e-86689f71140f.png)
Please help me, it disconnect

**Comment by TheSunShower** [comment]
> Please help me, it disconnect

It's not a disconnect. It's a crash when you set the AI to follow mode, caused by Routing issue. There should be an error.txt file with a crash log looking like this

Error message:
Invalid Coordinates argument.

Stack trace:
Trace begun at src\Task\Route.pm line 105
Task::Route::new('Task::Route', 'field', 'Field=HASH(0x78e6e04)', 'actor', 'Actor::You=HASH(0x4166574)', 'x', undef, 'y', undef, 'maxDistance', undef, 'maxTime', undef, 'distFromGoal', 1, 'pyDistFromGoal', undef, 'notifyUponArrival', undef, 'avoidWalls', undef) called at src\Actor.pm line 769
Actor::route('Actor::You=HASH(0x4166574)', undef, undef, undef, 'distFromGoal', 1) called at src\AI.pm line 538
AI::ai_route(undef, undef, undef, 'distFromGoal', 1) called at src\AI.pm line 285
AI::ai_partyfollow at src\AI\CoreLogic.pm line 2594
AI::CoreLogic::processFollow at src\AI\CoreLogic.pm line 159
AI::CoreLogic::iterate at src\functions.pl line 880
main::mainLoop_initialized at src\functions.pl line 75
main::mainLoop at src\Interface.pm line 75
Interface::mainLoop('Interface::Console::Win32=HASH(0x4e86ee4)') called at openkore.pl line 97
main::__start at start.pl line 136

Died at this line:
  
* 	if (!defined $args{x} || !defined $args{y} || $args{x} < 0 || $args{y} < 0) {
  		ArgumentException->throw(error => "Invalid Coordinates argument.");

**Comment by alisonrag** [comment]
> > Please help me, it disconnect
> 
> It's not a disconnect. It's a crash when you set the AI to follow mode, caused by Routing issue. There should be an error.txt file with a crash log looking like this
> 
> Error message:
> Invalid Coordinates argument.
> 
> Stack trace:
> Trace begun at src\Task\Route.pm line 105
> Task::Route::new('Task::Route', 'field', 'Field=HASH(0x78e6e04)', 'actor', 'Actor::You=HASH(0x4166574)', 'x', undef, 'y', undef, 'maxDistance', undef, 'maxTime', undef, 'distFromGoal', 1, 'pyDistFromGoal', undef, 'notifyUponArrival', undef, 'avoidWalls', undef) called at src\Actor.pm line 769
> Actor::route('Actor::You=HASH(0x4166574)', undef, undef, undef, 'distFromGoal', 1) called at src\AI.pm line 538
> AI::ai_route(undef, undef, undef, 'distFromGoal', 1) called at src\AI.pm line 285
> AI::ai_partyfollow at src\AI\CoreLogic.pm line 2594
> AI::CoreLogic::processFollow at src\AI\CoreLogic.pm line 159
> AI::CoreLogic::iterate at src\functions.pl line 880
> main::mainLoop_initialized at src\functions.pl line 75
> main::mainLoop at src\Interface.pm line 75
> Interface::mainLoop('Interface::Console::Win32=HASH(0x4e86ee4)') called at openkore.pl line 97
> main::__start at start.pl line 136
> 
> Died at this line:
> 
> * if (!defined $args{x} || !defined $args{y} || $args{x} < 0 || $args{y} < 0) {
>   ArgumentException->throw(error => "Invalid Coordinates argument.");

seems like master $char->{party}{users}{$master{id}}{pos}{x} is not defined.
it always happen or only happens when change map / lost master?

**Comment by alisonrag** [comment]
> ![image](https://user-images.githubusercontent.com/87201145/125321907-5b6def00-e367-11eb-9f1e-86689f71140f.png)
> Please help me, it disconnect

the error auto explain what you need to do...
go to control/sys.txt and add `vRO_auth ` to `loadPlugins_list`

**Comment by abc9900** [comment]
> > > Please help me, it disconnect
> > 
> > 
> > It's not a disconnect. It's a crash when you set the AI to follow mode, caused by Routing issue. There should be an error.txt file with a crash log looking like this
> > Error message:
> > Invalid Coordinates argument.
> > Stack trace:
> > Trace begun at src\Task\Route.pm line 105
> > Task::Route::new('Task::Route', 'field', 'Field=HASH(0x78e6e04)', 'actor', 'Actor::You=HASH(0x4166574)', 'x', undef, 'y', undef, 'maxDistance', undef, 'maxTime', undef, 'distFromGoal', 1, 'pyDistFromGoal', undef, 'notifyUponArrival', undef, 'avoidWalls', undef) called at src\Actor.pm line 769
> > Actor::route('Actor::You=HASH(0x4166574)', undef, undef, undef, 'distFromGoal', 1) called at src\AI.pm line 538
> > AI::ai_route(undef, undef, undef, 'distFromGoal', 1) called at src\AI.pm line 285
> > AI::ai_partyfollow at src\AI\CoreLogic.pm line 2594
> > AI::CoreLogic::processFollow at src\AI\CoreLogic.pm line 159
> > AI::CoreLogic::iterate at src\functions.pl line 880
> > main::mainLoop_initialized at src\functions.pl line 75
> > main::mainLoop at src\Interface.pm line 75
> > Interface::mainLoop('Interface::Console::Win32=HASH(0x4e86ee4)') called at openkore.pl line 97
> > main::__start at start.pl line 136
> > Died at this line:
> > 
> > * if (!defined $args{x} || !defined $args{y} || $args{x} < 0 || $args{y} < 0) {
> >   ArgumentException->throw(error => "Invalid Coordinates argument.");
> 
> seems like master $char->{party}{users}{$master{id}}{pos}{x} is not defined.
> it always happen or only happens when change map / lost master?

It's always happen when idle, if master always active (moving/attacking...), kore will be ok. And when master inactive (sitting or simply do nothing), kore will disconnect after few sec.

**Comment by ClarkNguyen** [comment]
you guys can use skill ID in tables/SKILL_id_handle.txt instead skill name, it's work

**Comment by ya4ept** [comment]
I checked, `buyAuto` works without problems!

auto-disconnected and skill usage were corrected here: #3460

**Comment by TheSunShower** [comment]
> I checked, `buyAuto` works without problems!
> 
> auto-disconnected and skill usage were corrected here: #3460

Can confirm autobuy/sell/storage works with out problem since the original post I made.

However, even when using the #3460 branch it doesn't stop the disconnecting problem. It helps with the relog though because no more stacking relog timer.

**Comment by Pureaznangel** [comment]
Me, too.

**Comment by chumlacklx** [comment]
![image](https://user-images.githubusercontent.com/87187797/125400810-8e05ff00-e3dc-11eb-9f36-bacf1f7f0ab8.png)
Disconnect occur oftenly may be due to server had new updates this morning

**Comment by TheSunShower** [comment]
> Disconnect occur oftenly may be due to server had new updates this morning

I was talking about the original disconnecting issue with the VTC token expiring and stacking timers.

**Comment by chrislong93** [comment]
> > I checked, `buyAuto` works without problems!
> > auto-disconnected and skill usage were corrected here: #3460
> 
> Can confirm autobuy/sell/storage works with out problem since the original post I made.
> 
> However, even when using the #3460 branch it doesn't stop the disconnecting problem. It helps with the relog though because no more stacking relog timer.

hmm weird I couldnt do autobuy with yesterday's master but I just downloaded the master and autobuy works. 

However, I get disconnected every 2 minutes? Did something happen during this morning's maintenance?

**Comment by TheSunShower** [comment]
> However, I get disconnected every 2 minutes? Did something happen during this morning's maintenance?

There are new files on the clients.

2021-07-13_live_data_124_124_1626097296.gpf
2021-07-13_live_data_124_124_1626097296.rgz
2021-07-13_live_data_126_126_1626104523.gpf
2021-07-13_live_data_127_127_1626145146.gpf

**Comment by farsmile90** [comment]
> > However, I get disconnected every 2 minutes? Did something happen during this morning's maintenance?
> 
> There are new files on the clients.
> 
> 2021-07-13_live_data_124_124_1626097296.gpf
> 2021-07-13_live_data_124_124_1626097296.rgz
> 2021-07-13_live_data_126_126_1626104523.gpf
> 2021-07-13_live_data_127_127_1626145146.gpf

Is there any solution fix disconnected every 1 min ?

**Comment by chrislong93** [comment]
![image](https://user-images.githubusercontent.com/26244945/125444566-03b4e6d9-ccd4-4e6a-b5c6-b93146ee097a.png)

Debug

**Comment by sctnightcore** [comment]
Discord server :p 
https://discord.gg/mPYvkJg7Du

**Comment by hailua28** [comment]
![abc](https://user-images.githubusercontent.com/87394162/125521760-f419fe8e-66d9-4977-8ff3-4dd033f967db.jpg)
How about this error?

**Comment by TheSunShower** [comment]
> How about this error?

The stacking timer was fixed in #3460 but not in master yet.

**Comment by chumlacklx** [comment]
Anyone have idea how to fix disconnect every 1 min ?

**Comment by chrislong93** [comment]
> Discord server :p
> https://discord.gg/mPYvkJg7Du

@nqtoan86 need you to join us in the discussion

**Comment by chumlacklx** [comment]
Anyone help with usually disconnect every 30second plz :v

**Comment by royalgarter** [comment]
> Anyone help with usually disconnect every 30second plz :v

@chumlacklx Flushing this thread won't help in any mean. Instead let's give our developers some detail clues if you have any.

**Comment by chumlacklx** [comment]
> > However, I get disconnected every 2 minutes? Did something happen during this morning's maintenance?
> 
> There are new files on the clients.
> 
> 2021-07-13_live_data_124_124_1626097296.gpf
> 2021-07-13_live_data_124_124_1626097296.rgz
> 2021-07-13_live_data_126_126_1626104523.gpf
> 2021-07-13_live_data_127_127_1626145146.gpf



> > Anyone help with usually disconnect every 30second plz :v
> 
> @chumlacklx Flushing this thread won't help in any mean. Instead let's give our developers some detail clues if you have any.

![image](https://user-images.githubusercontent.com/87187797/125573982-c324733e-5d50-4d0d-9bed-586cc7f4ab3a.png)
There are someone who found some new on updates change on 13 July. May be those files cause disconnect frequently.

**Comment by ya4ept** [comment]
It has nothing to do with protection:
**2021-07-13_live_data_124_124_1626097296.gpf:**
  idnum2itemresnametable.txt
  num2itemresnametable.txt
**2021-07-13_live_data_124_124_1626097296.rgz**
  System\iteminfo.lub
**2021-07-13_live_data_126_126_1626104523.gpf**
  questid2display.txt
**2021-07-13_live_data_127_127_1626145146.gpf**
  manner.txt

**Comment by hailua28** [comment]
![abc1](https://user-images.githubusercontent.com/87394162/125590150-6ccc68c5-6585-4b89-a148-26c4ef9507f3.jpg)
Can you give a simple guide?

**Comment by ya4ept** [comment]
https://openkore.com/wiki/Main_Page
![image](https://user-images.githubusercontent.com/7117363/125595593-7abad21c-9457-4df3-b171-911bdd8e6c22.png)

**Comment by ClarkNguyen** [comment]
@ya4ept do you have any idea why disconnected from map server happen every one minute? Maybe they implement some ping pong mechanism to keep accessToken alive in the client?

**Comment by hailua28** [comment]
> @ ya4ept bạn có biết tại sao cứ sau một phút lại bị ngắt kết nối với máy chủ bản đồ không? Có thể họ thực hiện một số cơ chế bóng bàn để giữ accessToken tồn tại trong máy khách?

Có xài Zalo không bạn cho mình xin Zalo để hỏi 1 chút nha !

**Comment by sctnightcore** [comment]
> Discord server :p
> https://discord.gg/mPYvkJg7Du

ping

**Comment by ya4ept** [comment]
@ClarkNguyen they just turned on nProtect, until this moment it did not work:

![image](https://user-images.githubusercontent.com/7117363/125600005-48e582db-e18f-41a6-a845-c349b4c1767e.png)

OpenKore should respond to the request for `09CF` or will be disabled. For this we need to fix Poseidon

**Comment by Pureaznangel** [comment]
Thanks for the useful information. This helps a lot.

**Comment by TheSunShower** [comment]
I can confirm that with the update on 13/07/2020 VTC turned on Gameguard so now please follow below instruction to start botting without getting disconnected.

Note that one PC can only run one Openkore. OpenKore/Poseidon should be run on VM while Ragexe client should be run natively because nProtect hate VM and nProtect detect OpenKore. Running multiple OpenKore on one machine resulting in them all disconnecting at once.

> https://openkore.com/wiki/Main_Page
> ![image](https://user-images.githubusercontent.com/7117363/125595662-99a06b4c-c784-47bb-a851-48828d4d853c.png)

At the moment everything are functional but it's quite limited as one bot per PC.

**Comment by needHelp99** [comment]
i downloaded the latest version of Openkore, and opened Poseidon -> Openkore on a separate virtual machine. But it keeps losing connection. (This virtual machine does not install vRO of VTC, only Openkore, only one Openkore) please support me. Thanks for reading.

**Comment by hailua28** [comment]
> Tôi có thể xác nhận rằng với bản cập nhật ngày 13/07/2020 VTC đã bật Gameguard nên bây giờ hãy làm theo hướng dẫn dưới đây để bắt đầu bot mà không bị ngắt kết nối.
> 
> Lưu ý rằng một PC chỉ có thể chạy một Openkore. OpenKore / Poseidon nên được chạy trên VM trong khi ứng dụng khách Ragexe phải được chạy nguyên bản vì nProtect ghét VM và nProtect phát hiện OpenKore. Chạy nhiều OpenKore trên một máy dẫn đến tất cả chúng đều bị ngắt kết nối cùng một lúc.
> 
> > https://openkore.com/wiki/Main_Page
> > ![hình ảnh](https://user-images.githubusercontent.com/7117363/125595662-99a06b4c-c784-47bb-a851-48828d4d853c.png)
> 
> Hiện tại, mọi thứ đều hoạt động nhưng nó khá hạn chế vì một bot trên mỗi PC.

![abc2](https://user-images.githubusercontent.com/87394162/125661943-68b53ca2-830a-4a1a-b115-0cfa90094109.jpg)
I am still stuck in this error.

**Comment by alisonrag** [comment]
> I am still stuck in this error.

the error auto explain what you need to do...
go to `control/sys.txt` and add `vRO_auth ` to `loadPlugins_list`

**Comment by ClarkNguyen** [comment]
@alisonrag current ragexe need be launch with the launcher, can't executable as standalone, how can I input "1rag1 /account:poseidon.xml" as parameter for ragexe?

**Comment by hailua28** [comment]
> @alisonrag current ragexe need be launch with the launcher, can't executable as standalone, how can I input "1rag1 /account:poseidon.xml" as parameter for ragexe?

Ông hiểu không chỉ giúp tôi được không ? go to control/sys.txt and add vRO_auth to loadPlugins_list là sao ta ?

**Comment by ClarkNguyen** [comment]
@hailua28 
1. Go control folder, find sys.txt then open it with notepad.
2. Find loadPlugins_list and add vRO_auth at the end of line.
Example:
```loadPlugins_list macro,profiles,breakTime,raiseStat,raiseSkill,map,reconnect,eventMacro,item_weight_recorder,xconf,vRO_auth```

**Comment by hailua28** [comment]
> @hailua28
> 
> 1. Go to control folder, find sys.txt then open it with notepad.
> 2. Find loadPlugins_list and add vRO_auth at the end of line.
>    Example:
>    `loadPlugins_list macro,profiles,breakTime,raiseStat,raiseSkill,map,reconnect,eventMacro,item_weight_recorder,xconf,vRO_auth`

Đã test nhưng vẫn không được, không biết còn bị lỗi gì không !

**Comment by TheSunShower** [comment]
This is getting out of hand so just letting you know this is an issue discussion with VRO server not tech support to teach you how to use OpenKore. Join the discord link [https://discord.gg/mPYvkJg7Du](https://discord.gg/mPYvkJg7Du) and select vro_vietnam chat for help. Don't do it here.

If you got the OpenKore working but something else came up feel free to post it here. If you couldn't even get the bot running please check out tutorial, or visit the discord for help.

**Comment by chumlacklx** [comment]
Finally vRO like cRO must use poseidon to bot. That is unhappy information :(

**Comment by nnb1988** [comment]
> @hailua28
> 
> 1. Go to control folder, find sys.txt then open it with notepad.
> 2. Find loadPlugins_list and add vRO_auth at the end of line.
>    Example:
>    `loadPlugins_list macro,profiles,breakTime,raiseStat,raiseSkill,map,reconnect,eventMacro,item_weight_recorder,xconf,vRO_auth`

Can you check your email ?

**Comment by nnb1988** [comment]
> @hailua28
> 
> 1. Go to control folder, find sys.txt then open it with notepad.
> 2. Find loadPlugins_list and add vRO_auth at the end of line.
>    Example:
>    `loadPlugins_list macro,profiles,breakTime,raiseStat,raiseSkill,map,reconnect,eventMacro,item_weight_recorder,xconf,vRO_auth`

can you check your email

**Comment by TheSunShower** [comment]
OpenKore crash if it goes online before "followTarget" and try to route to target positon after "followTarget" go online. Suggestion to set bot to idle instead, or set "followTarget" position after target go online to avoid crashing.

wxstart cause any party command to force disconnection. Trade command works fine so I think it's just the issue with Party command.

**Comment by hiepsichim** [comment]
**Disconnected from Map Server, connecting to Account Server in 44 seconds...**
Help me please :(

**Comment by maichoi9x** [comment]
> Finally vRO like cRO must use poseidon to bot. That is unhappy information :(

ông ơi ông bot dc chưa.chỉ tôi với
add zalo dc ko 0973578038
tôi tìm fb ông ko dc
fb tôi : Hưng Ngô

**Comment by maichoi9x** [comment]
> @hailua28
> 
> 1. Go to control folder, find sys.txt then open it with notepad.
> 2. Find loadPlugins_list and add vRO_auth at the end of line.
>    Example:
>    `loadPlugins_list macro,profiles,breakTime,raiseStat,raiseSkill,map,reconnect,eventMacro,item_weight_recorder,xconf,vRO_auth`

ông ơi ông bot dc chưa.chỉ tôi với
add zalo dc ko 0973578038
fb tôi : Hưng Ngô

**Comment by ya4ept** [comment]
@maichoi9x use only english please!

**Comment by hiepsichim** [comment]
> @maichoi9x use only english please!
** " Disconnected from Map Server, connecting to Account Server in 44 seconds... " **
Can you explain it, please :(

**Comment by hiepsichim** [comment]
@ya4ept 
**Disconnected from Map Server, connecting to Account Server in 44 seconds...**
Can you explain it, please :(

**Comment by maichoi9x** [comment]
> @maichoi9x use only english please!

sr i'm not speak english well ^^!

**Comment by maichoi9x** [comment]
> @ya4ept
> **Disconnected from Map Server, connecting to Account Server in 44 seconds...**
> Can you explain it, please :(

add zalo help me pls 0973578038

**Comment by hailua28** [comment]
Hi 
![abc2](https://user-images.githubusercontent.com/87394162/126048904-9f12a1d0-6df2-482f-9fa9-47223c2f0f09.jpg)
@ya4ept  

How to solve this problem !

**Comment by hailua28** [comment]
hi @ya4ept 

How to solve this problem !
![abc 2](https://user-images.githubusercontent.com/87394162/126048950-088a9e73-98a8-4ef1-87db-fd2de44c8021.jpg)

**Comment by hailua28** [comment]
@ya4ept 
![abc 3](https://user-images.githubusercontent.com/87394162/126048980-df43708d-69bf-4c9c-8a13-bf2ce57f8c1a.jpg)

**Comment by maichoi9x** [comment]
> @ ya4ept
> ![abc 3](https://user-images.githubusercontent.com/87394162/126048980-df43708d-69bf-4c9c-8a13-bf2ce57f8c1a.jpg)

ông ơi cho tôi zalo hay fb tôi hỏi xíu về bot dc ko

**Comment by chumlacklx** [comment]
> hi @ya4ept
> 
> How to solve this problem !
> ![abc 2](https://user-images.githubusercontent.com/87394162/126048950-088a9e73-98a8-4ef1-87db-fd2de44c8021.jpg)

Server has turned on Gameguard so you coudn’t run normally bot but poseidon can. Try the follow step on openkore main page and do step to step as guided

**Comment by maichoi9x** [comment]
> > chào @ ya4ept
> > Làm thế nào để giải quyết vấn đề này !
> > ![abc 2](https://user-images.githubusercontent.com/87394162/126048950-088a9e73-98a8-4ef1-87db-fd2de44c8021.jpg)
> 
> Máy chủ đã bật Gameguard nên bạn không thể chạy bot bình thường nhưng poseidon thì có thể. Hãy thử làm theo bước trên trang chính của openkore và thực hiện từng bước theo hướng dẫn

poseidon pls ... how to use it

**Comment by hiepsichim** [comment]
Dear @chumlacklx  !
Can you give detailed instructions on how to do it?
I don't understand how to do Poseidon.
Thank you very much !

**Comment by DuongBien2204** [comment]
Help me start 'ragexe 1rag1 /account:poseidon.xml' Bad excute error  https://i.imgur.com/tR6KLFk.png

**Comment by talkervn** [comment]
@DuongBien2204 can you teach me "how to config and run poseidon server step by step"?
thanks.

**Comment by talkervn** [comment]
Vietnamese men are selfish.
Asking the tool you are doing to what step, no one answered.
Meanwhile up here ask how the bot rumbles.
Hiding bot tool from Vietnamese people for profit?
That's selfish!!!

**Comment by chimbenhat** [comment]
> > Help me start 'ragexe 1rag1 /account:poseidon.xml' Bad excute error
> > https://i.imgur.com/tR6KLFk.png
> 
> u need to add other parameters to execute:
> 
> ```
> D:\abcbucu\Ragexe.exe 1rag1 User=anyusername Token=Foo BToken=Bar /account:poseidon.xml
> ```

still cannot connect to Poseidon server :( it connect to login screen showing "waiting to connect"  then " cannot connect to server" T.T

**Comment by leaf8831** [comment]
help me poseidon 
[https://uphinh.org/image/screenshot-8.972gqu](url)

**Comment by leaf8831** [comment]
![Screenshot (8)](https://user-images.githubusercontent.com/87678131/126241457-c337da62-ee9f-4f60-b98a-0e399b7963bf.png)
help me poseidon

**Comment by ya4ept** [comment]
Read this thread from the beginning! Stop asking the same question. I'm losing my patience!

**Comment by thu0890** [comment]
![image](https://user-images.githubusercontent.com/87684092/126256917-fad3ab6d-8cd9-40de-8160-e54aa858b957.png)
hi sir ! Can you help me this bug ? :(

**Comment by vclvclvn** [comment]
> Read this thread from the beginning! Stop asking the same question. I'm losing my patience!

totally agree. They should read and try and do some research. This is not instant noddle. We are willing to help, but we are not slave that make everything ready for you. Use your brainnnnnnnnn guys.

**Comment by chimbenhat** [comment]
> > Read this thread from the beginning! Stop asking the same question. I'm losing my patience!
> 
> totally agree. They should read and try and do some research. This is not instant noddle. We are willing to help, but we are not slave that make everything ready for you. Use your brainnnnnnnnn guys.



> > Help me start 'ragexe 1rag1 /account:poseidon.xml' Bad excute error
> > https://i.imgur.com/tR6KLFk.png
> 
> u need to add other parameters to execute:
> 
> ```
> D:\abcbucu\Ragexe.exe 1rag1 User=anyusername Token=Foo BToken=Bar /account:poseidon.xml
> ```

Hi, can you help me with this, i did  step by step as u guide but when trying to connect to poseidon server, it only show " waiting to connect" then " cannot connect to server", no character selection, this is my poseidon.txt file
# Ragnarok Server
# Here you'll define the IP Address and the Port where Poseidon
# will keep waiting for your ragnarok online client to connect.
ragnarokserver_ip=127.0.0.1
ragnarokserver_port=6900

# Query Server
# Here you'll define the IP Address and the Port where Poseidon
# will keep waiting for open kore to connect and send the GG/HS queries.
queryserver_ip=127.0.0.1
queryserver_port=24390

# Server Type
# Here you have to specify your current server type in order
# to the poseidon operate properly !
# The available server types for now are : Default, bRO_.* (check servertypes.txt)
# You should modify this if you're having problems with char list.
server_type=bRO_2016-11-08a

# Char Block Size
# Here you can specify the desired CharBlockSize your client requires
# The available block sizes are : 106, 108, 112, 116, 128, 132, 136, 140, 144, 145, 147 and 155
CharBlockSize=116

debug=0

hope u can help :(

**Comment by datxu0410** [comment]
Dear ya4ept,
Please check this errors, can't connect to server vRO went open star_poseidon.exe
Thanks

[errors.txt](https://github.com/OpenKore/openkore/files/6846272/errors.txt)

**Comment by datxu0410** [comment]
Dear ya4ept,
Please check this errors, can't connect to server vRO went open star_poseidon.exe
Thanks
[errors.txt](https://github.com/OpenKore/openkore/files/6846342/errors.txt)

**Comment by HaiPhan1989** [comment]
please show me bot raganarok vtc :( zalo 0335670940 and ft.candylee@gmail.com

**Comment by DuongBien2204** [comment]
> làm ơn cho tôi xem bot raganarok vtc :( zalo 0335670940 and [ft.candylee@gmail.com](mailto:ft.candylee@gmail.com)

You should look at the manual and do the research.

**Comment by nnduylc** [comment]
> ![abc 2](https://user-images.githubusercontent.com/87394162/126048950-088a9e73-98a8-4ef1-87db-fd2de44c8021.jpg)

Bot được chưa ông tôi cũng bị thế,
để XKore =0 thì chơi đc 50s là out
còn để XKore = 1 báo lỗi này Unable to inject  netredirect.dll 
> How to solve this problem !
![image](https://user-images.githubusercontent.com/88880096/129330964-49fc84e3-4280-47fa-8ea7-1fee1c7fdb6a.png)

**Comment by thongchim93** [comment]
i'm vietnamese i don't know how to install, can anyone help me to install, i will send teamviewer to install it for me, thank you very much

**Comment by thongchim93** [comment]
i'm vietnamese i don't know how to install, can anyone help me to install, i will send teamviewer to install it for me, thank you very much

**Comment by talkervn** [comment]
How to dual client in vro? Please tell me. Thx you.
